---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: posijon/slci

inputs:
  - name: version
outputs:
  - name: version-hvm

run:
  path: bosh-linux-stemcell-builder/ci/tasks/make-hvm-version.sh
