---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: posijon/slci

inputs:
  - name: version
  - name: bosh-linux-stemcell-builder
outputs:
  - name: hvm-version-info

run:
  path: bosh-linux-stemcell-builder/ci/tasks/make-hvm-version.sh
